
export const SET_TOKEN = 'SET_TOKEN'
export const SET_ACCOUNT = 'SET_ACCOUNT'
export const SET_LOGOUT = 'SET_LOGOUT'
export const SET_NULL = 'SET_NULL'

export const UP_VIDEO = 'UP_VIDEO'
export const UP_SUCCEEDED = 'UP_SUCCEEDED'
export const UP_FAILED = 'UP_FAILED'

export const FETCH_SUCCEEDED = 'FETCH_SUCCEEDED'
export const FETCH_FAILED = 'FETCH_FAILED'

export const UP_PROGRESS = 'UP_PROGRESS'

export const CREATE_FOLDER = 'CREATE_FOLDER'
export const CREATE_FOLDER_SUCCEEDED = 'CREATE_FOLDER_SUCCEEDED'
export const CREATE_FOLDER_FAILED = 'CREATE_FOLDER_FAILED'

export const GET_FOLDER = 'GET_FOLDER'
export const GET_FOLDER_SUCCEEDED = 'GET_FOLDER_SUCCEEDED'
export const GET_FOLDER_FAILED = 'GET_FOLDER_FAILED'
